from __future__ import annotations

import json
from pathlib import Path
from typing import List, Dict, Optional

from lark.lexer import Token

from constructs import FunctionDeclaration, Block, ArgumentsDeclaration, Constant, VariableDeclaration, Namespace, \
    Start, \
    Construct, ExpressionStatement, RunExpression, Assignment, AdditionOperation, VariableReference, OrOperation, \
    EqualityOperation, UnaryNotOperation, McfcNamespace, AndOperation, UnequalityOperation, LessThenOperation, \
    LessThenEqualsOperation, GreaterThenOperation, GreaterThenEqualsOperation, SubtractionOperation, \
    MultiplicationOperation, DivisionOperation, UnaryPlusOperation, UnaryMinusOperation, ModuloOperation
from instructions import StoreInstruction, RunInstruction, \
    AdditionInstruction, EqualityInstruction, Instruction, InvertInstruction, \
    CallIfZeroInstruction, CallIfNotZeroInstruction, LessThenInstruction, UnequalityInstruction, \
    LessThenEqualsInstruction, GreaterThenEqualsInstruction, GreaterThenInstruction, SubtractionInstruction, \
    MultiplicationInstruction, DivisionInstruction
from symboltable import BuiltinType, BlockScope, Variable, Type
from visitor import Visitor


class NameManager:
    def __init__(self, namespace: Namespace):
        self.registers: List[Variable] = []
        self.function_count: int = 0
        self.namespace: Namespace = namespace

    def create_register(self, type_: Type):
        self.registers.append(BlockScope.LocalVariable(McfcNamespace(), f"r{len(self.registers)}", type_))
        return self.registers[-1]

    def get_register(self, index: int = 0):
        return self.registers[-1 - index]

    def free_register(self):
        self.registers.pop()

    def create_function(self):
        self.function_count += 1
        return f"{self.function_count}"


class CodeGenerator(Visitor):
    def __init__(self):
        self.namespace_: Namespace = None
        self.functions: Dict[str, List[Instruction]] = {}
        self.variables: set = set()
        self.events: Dict = {}
        self.name_manager: Optional[NameManager] = None

    def write_to_files(self, output_directory: Path):
        with output_directory.joinpath("pack.mcmeta").open("w+") as pack_mcmeta:
            metadata = {"pack": {
                "pack_version": 1,
                "description": "Generated by MCFunction compiler"
            }}
            json.dump(metadata, pack_mcmeta)
        functions_dir = output_directory.joinpath("data").joinpath(self.namespace_.name).joinpath("functions")
        functions_dir.mkdir(parents=True)
        for function_name in self.functions:
            with functions_dir.joinpath(f"{function_name}.mcfunction").open("w+") as function_file:
                for instruction in self.functions[function_name]:
                    function_file.write(instruction.to_string())
                    function_file.write("\n")

    def __default__(self, construct: Construct):
        raise Exception(construct)

    def start(self, start: Start):
        start.code = []
        for child in start.children:
            child.accept(self)
            start.code += child.code
        self.functions["init"] = start.code
        for function_ in self.functions:
            print(f"{function_.upper()}:")
            for instruction in self.functions[function_]:
                print(instruction.to_string())

    def namespace(self, namespace: Namespace):
        self.namespace_ = namespace
        self.name_manager = NameManager(namespace)
        namespace.code = []

    def variable_declaration(self, declaration: VariableDeclaration):
        if isinstance(declaration.type_ref.type, BuiltinType):
            self.variables.add(declaration.reference.name)
        else:
            raise NotImplementedError
        if declaration.expression is not None:
            declaration.expression.accept(self)
            declaration.code = declaration.expression.code
            declaration.code.append(StoreInstruction(declaration.reference.target, self.name_manager.get_register()))
            self.name_manager.free_register()
        else:
            declaration.code = []

    def constant(self, constant: Constant):
        constant.code = [StoreInstruction(self.name_manager.create_register(constant.type), constant)]

    def arguments(self, arguments: ArgumentsDeclaration):
        arguments.code = []
        for child in arguments.children:
            child.accept(self)
            arguments.code += child.code

    def function_declaration(self, declaration: FunctionDeclaration):
        declaration.arguments.accept(self)
        declaration.block.accept(self)
        code = declaration.arguments.code + declaration.block.code
        self.functions[declaration.reference.name] = code
        declaration.code = []

    def block(self, block: Block):
        block.code = []
        for statement in block.statements:
            statement.accept(self)
            block.code += statement.code

    def expression_statement(self, statement: ExpressionStatement):
        statement.expression.accept(self)
        statement.code = statement.expression.code

    def run_expression(self, expression: RunExpression):
        expression.code = [RunInstruction(expression.command)]

    def assignment(self, assignment: Assignment):
        assignment.expression.accept(self)
        assignment.code = assignment.expression.code
        assignment.code.append(StoreInstruction(assignment.ref.target, self.name_manager.get_register()))
        self.name_manager.free_register()

    def or_operation(self, operation: OrOperation):
        operation.left_expression.accept(self)
        operation.right_expression.accept(self)
        function_name = self.name_manager.create_function()
        operation.code = operation.left_expression.code + [
            CallIfZeroInstruction(self.name_manager.get_register(), self.namespace_, function_name)
        ]
        self.functions[function_name] = operation.right_expression.code
        self.name_manager.free_register()

    def and_operation(self, operation: AndOperation):
        operation.left_expression.accept(self)
        operation.right_expression.accept(self)
        function_name = self.name_manager.create_function()
        operation.code = operation.left_expression.code + [
            CallIfNotZeroInstruction(self.name_manager.get_register(), self.namespace_, function_name)
        ]
        self.functions[function_name] = operation.right_expression.code
        self.name_manager.free_register()

    def equality_operation(self, operation: EqualityOperation):
        operation.left_expression.accept(self)
        operation.right_expression.accept(self)
        operation.code = operation.left_expression.code + operation.right_expression.code + [
            EqualityInstruction(self.name_manager.get_register(1), self.name_manager.get_register())
        ]
        self.name_manager.free_register()

    def unequality_operation(self, operation: UnequalityOperation):
        operation.left_expression.accept(self)
        operation.right_expression.accept(self)
        operation.code = operation.left_expression.code + operation.right_expression.code + [
            UnequalityInstruction(self.name_manager.get_register(1), self.name_manager.get_register()),
        ]
        self.name_manager.free_register()

    def less_then_operation(self, operation: LessThenOperation):
        operation.left_expression.accept(self)
        operation.right_expression.accept(self)
        operation.code = operation.left_expression.code + operation.right_expression.code + [
            LessThenInstruction(self.name_manager.get_register(1), self.name_manager.get_register()),
        ]
        self.name_manager.free_register()

    def less_then_equals_operation(self, operation: LessThenEqualsOperation):
        operation.left_expression.accept(self)
        operation.right_expression.accept(self)
        operation.code = operation.left_expression.code + operation.right_expression.code + [
            LessThenEqualsInstruction(self.name_manager.get_register(1), self.name_manager.get_register()),
        ]
        self.name_manager.free_register()

    def greater_then_operation(self, operation: GreaterThenOperation):
        operation.left_expression.accept(self)
        operation.right_expression.accept(self)
        operation.code = operation.left_expression.code + operation.right_expression.code + [
            GreaterThenInstruction(self.name_manager.get_register(1), self.name_manager.get_register()),
        ]
        self.name_manager.free_register()

    def greater_then_equals_operation(self, operation: GreaterThenEqualsOperation):
        operation.left_expression.accept(self)
        operation.right_expression.accept(self)
        operation.code = operation.left_expression.code + operation.right_expression.code + [
            GreaterThenEqualsInstruction(self.name_manager.get_register(1), self.name_manager.get_register()),
        ]
        self.name_manager.free_register()

    def addition_operation(self, operation: AdditionOperation):
        operation.left_expression.accept(self)
        operation.right_expression.accept(self)
        operation.code = operation.left_expression.code + operation.right_expression.code + [
            AdditionInstruction(self.name_manager.get_register(1), self.name_manager.get_register())
        ]
        self.name_manager.free_register()

    def subtraction_operation(self, operation: SubtractionOperation):
        operation.left_expression.accept(self)
        operation.right_expression.accept(self)
        operation.code = operation.left_expression.code + operation.right_expression.code + [
            SubtractionInstruction(self.name_manager.get_register(1), self.name_manager.get_register())
        ]
        self.name_manager.free_register()

    def multiplication_operation(self, operation: MultiplicationOperation):
        operation.left_expression.accept(self)
        operation.right_expression.accept(self)
        operation.code = operation.left_expression.code + operation.right_expression.code + [
            MultiplicationInstruction(self.name_manager.get_register(1), self.name_manager.get_register())
        ]
        self.name_manager.free_register()

    def division_operation(self, operation: DivisionOperation):
        operation.left_expression.accept(self)
        operation.right_expression.accept(self)
        operation.code = operation.left_expression.code + operation.right_expression.code + [
            DivisionInstruction(self.name_manager.get_register(1), self.name_manager.get_register())
        ]
        self.name_manager.free_register()

    def modulo_operation(self, operation: ModuloOperation):
        operation.left_expression.accept(self)
        operation.right_expression.accept(self)
        operation.code = operation.left_expression.code + operation.right_expression.code + [
            ModuloInstruction(self.name_manager.get_register(1), self.name_manager.get_register())
        ]
        self.name_manager.free_register()

    def unary_plus_operation(self, operation: UnaryPlusOperation):
        operation.expression.accept(self)
        operation.code = operation.expression.code

    def unary_minus_operation(self, operation: UnaryMinusOperation):
        operation.expression.accept(self)
        operation.code = operation.expression.code + [
            StoreInstruction(self.name_manager.get_register(), Constant(Token("INT", "-1"))),
            MultiplicationInstruction(self.name_manager.get_register(1), self.name_manager.get_register())
        ]
        self.name_manager.free_register()

    def unary_not_operation(self, operation: UnaryNotOperation):
        operation.expression.accept(self)
        operation.code = operation.expression.code + [InvertInstruction(self.name_manager.get_register())]

    def variable_ref(self, reference: VariableReference):
        reference.code = [StoreInstruction(self.name_manager.create_register(reference.type), reference.target)]
